cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.6
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
    ssl: false
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "vuongnd-k8s-07"
        devices:
          - name: "sdb"
            config:
              osdsPerDevice: "1"
ingress:
  dashboard:
    host:
      name: ceph.vuongnd.local
      path: "/ceph-dashboard(/|$)(.*)"
    ingressClassName: nginx